"""Git pre-commit hook installation for local AST safety guards."""

from __future__ import annotations

import os
import stat
from pathlib import Path

from ..logging_config import get_logger

logger = get_logger(__name__)

HOOK_TEMPLATE = """#!/bin/sh
# Pre-commit hook generated by futures-rag-lab AST code review system

echo "[*] Running AST Code Review and Safety Guard on staged files..."
uv run python -m src.review.cli --staged

EXIT_CODE=$?
if [ $EXIT_CODE -ne 0 ]; then
    echo "[!] Pre-commit safety check failed. Commit aborted."
    echo "[!] Please resolve blocking security violations before committing."
    exit $EXIT_CODE
fi

echo "[+] Code review safety checks passed."
exit 0
"""


def install_pre_commit_hook(repo_root: Path | str | None = None) -> Path:
    """Install pre-commit hook script into .git/hooks/pre-commit."""
    root = Path(repo_root) if repo_root else Path.cwd()
    git_dir = root / ".git"

    if not git_dir.exists() or not git_dir.is_dir():
        raise FileNotFoundError(f"Git directory not found at {git_dir}. Are you inside a Git repository?")

    hooks_dir = git_dir / "hooks"
    hooks_dir.mkdir(parents=True, exist_ok=True)

    hook_file = hooks_dir / "pre-commit"
    hook_file.write_text(HOOK_TEMPLATE, encoding="utf-8")

    # Grant executable permissions on Unix / POSIX
    try:
        current_stat = hook_file.stat()
        hook_file.chmod(current_stat.st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    except Exception as err:
        logger.debug("Could not set execute permission on %s: %s", hook_file, err)

    logger.info("Installed pre-commit hook at %s", hook_file)
    return hook_file
